// Generated by CoffeeScript 1.8.0
(function() {
  var executeScripts, gather_form_data, main, run_checker, set_options;

  gather_form_data = function(form) {
    var $form, data;
    $form = $(form);
    data = {};
    $form.find('input[name]').each(function() {
      var name, value;
      name = this.name;
      value = this.value;
      if (this.type === 'checkbox') {
        value = this.checked;
      }
      data[name] = value;
    });
    return data;
  };

  executeScripts = function(tabId, injectDetailsArray) {
    var callback, createCallback, i;
    createCallback = function(tabId, injectDetails, innerCallback) {
      return function() {
        return chrome.tabs.executeScript(tabId, injectDetails, innerCallback);
      };
    };
    callback = null;
    if (typeof tabId !== 'number') {
      injectDetailsArray = tabId;
      tabId = null;
    }
    i = injectDetailsArray.length - 1;
    while (i >= 0) {
      callback = createCallback(tabId, injectDetailsArray[i], callback);
      --i;
    }
    if (callback !== null) {
      callback();
    }
  };

  set_options = function(options) {
    return new Promise(function(resolve) {
      return chrome.storage.local.set({
        'options': options
      }, function() {
        return resolve();
      });
    });
  };

  run_checker = function(check_all_a_tags) {
    var options;
    options = gather_form_data('#form');
    options.check_all = check_all_a_tags;
    set_options(options).then(function() {
      return executeScripts([
        {
          file: "js/jquery-2.1.1.min.js"
        }, {
          file: "js/content_scripts/inspect_element.js"
        }
      ]);
    });
    return window.close();
  };

  main = function() {
    chrome.storage.local.get('options', function(data) {
      return $('#form input').each(function() {
        this.checked = data.options[this.name];
        return null;
      });
    });
    $('#check').click(function(e) {
      e.preventDefault();
      run_checker(true);
    });
    return $('#inspect').click(function(e) {
      e.preventDefault();
      run_checker(false);
    });
  };

  main();

}).call(this);
